#!/bin/bash

script_dir="$(dirname "$(realpath "$0")")"
cd "$script_dir"

patch node_modules/bigchaindb-driver/dist/node/Ed25519Keypair.js << EOF
28c28
<   this.publicKey = _bs2.default.encode(keyPair.publicKey);
---
>   this.publicKey = _bs2.default.encode(Buffer.from(keyPair.publicKey));
30,31c30,31
<   this.privateKey = _bs2.default.encode(keyPair.secretKey.slice(0, 32));
< }
\ No newline at end of file
---
>   this.privateKey = _bs2.default.encode(Buffer.from(keyPair.secretKey.slice(0, 32)));
> }
EOF
